name: publish

on:
  push:
    branches:
      - main
    paths:
      - '**/Cargo.toml'

jobs:
  crates:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Cargo Release
      run: |
        curl -fsSLo /tmp/cargo-release.tar.gz https://github.com/crate-ci/cargo-release/releases/download/v0.24.8/cargo-release-v0.24.8-x86_64-unknown-linux-gnu.tar.gz
        mkdir -p /tmp/cargo-release
        tar -C /tmp/cargo-release -xzf /tmp/cargo-release.tar.gz
        sudo mv /tmp/cargo-release/cargo-release /usr/local/bin
    - name: Release to crates.io
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
      run: |
        cargo release publish --execute --no-confirm
