name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: |
        STRAWBOAT_FREQ_COMPRESSION=1 cargo test --verbose
        STRAWBOAT_DICT_COMPRESSION=1 cargo test --verbose
        STRAWBOAT_RLE_COMPRESSION=1 cargo test --verbose
